// Generated by CoffeeScript 1.10.0
(function() {
  var EditorPackage,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = EditorPackage = (function(superClass) {
    extend(EditorPackage, superClass);

    function EditorPackage() {
      return EditorPackage.__super__.constructor.apply(this, arguments);
    }

    EditorPackage.prototype.name = "Editor";

    EditorPackage.prototype.Hotkeys = require("./hotkeys");

    EditorPackage.prototype.Commands = require("./commands");

    return EditorPackage;

  })(Vincent.Package);

}).call(this);
