// Generated by CoffeeScript 1.10.0
(function() {
  var CorePackage,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = CorePackage = (function(superClass) {
    extend(CorePackage, superClass);

    function CorePackage() {
      return CorePackage.__super__.constructor.apply(this, arguments);
    }

    CorePackage.prototype.name = "Core";

    CorePackage.prototype.Commands = require("./commands");

    CorePackage.prototype.Hotkeys = require("./hotkeys");

    CorePackage.prototype.Decorations = require("./decorations");

    CorePackage.prototype.Spells = [require("./spell.codeSpell"), require("./spell.superReferenceSpell"), require("./spell.referenceSpell"), require("./spell.standardLinkSpell"), require("./spell.markdownLinkSpell"), require("./spell.markdownImageSpell"), require("./spell.markdownImageLinkSpell")];

    CorePackage.prototype.Elements = [require("./element.divider"), require("./element.footnote"), require("./element.headline"), require("./element.quote"), require("./element.toc"), require("./element.listItem")];

    CorePackage.prototype.Composers = [require("./composer.richTextToDivider"), require("./composer.dividerRetainer"), require("./composer.richTextToFootnote"), require("./composer.footnoteRetainer"), require("./composer.richTextToHeadline"), require("./composer.headlineRetainer"), require("./composer.richTextToQuote"), require("./composer.quoteRetainer"), require("./composer.richTextToToc"), require("./composer.tocRetainer"), require("./composer.richTextToListItem"), require("./composer.listItemRetainer"), require("./composer.listItemOrderer")];

    CorePackage.prototype.Intents = require("./intents");

    return CorePackage;

  })(Vincent.Package);

}).call(this);
