module.exports = class CorePackage extends Vincent.Package
    name:"Core"
    Commands:require("./commands")
    Hotkeys:require("./hotkeys")
    Decorations:require("./decorations")
    Spells:[
        require("./spell.codeSpell")
        require("./spell.superReferenceSpell")
        require("./spell.referenceSpell")
        require("./spell.standardLinkSpell")
        require("./spell.markdownLinkSpell")
        require("./spell.markdownImageSpell")
        require("./spell.markdownImageLinkSpell")
    ]
    Elements:[
        require("./element.divider")
        require("./element.footnote")
        require("./element.headline")
        require("./element.quote")
        require("./element.toc")
        require("./element.listItem")
    ]
    Composers:[
        require("./composer.richTextToDivider")
        require("./composer.dividerRetainer")
        require("./composer.richTextToFootnote")
        require("./composer.footnoteRetainer")
        require("./composer.richTextToHeadline")
        require("./composer.headlineRetainer")
        require("./composer.richTextToQuote")
        require("./composer.quoteRetainer")
        require("./composer.richTextToToc")
        require("./composer.tocRetainer")
        require("./composer.richTextToListItem")
        require("./composer.listItemRetainer")
        require("./composer.listItemOrderer")
    ]
    Intents:require("./intents")
