// Generated by CoffeeScript 1.10.0
(function() {
  var Debugger;

  Debugger = (function() {
    function Debugger() {
      var i, len, prop, ref;
      this.saves = {};
      this.debugFunctions = ["time", "timeEnd", "debug", "log"];
      ref = this.debugFunctions;
      for (i = 0, len = ref.length; i < len; i++) {
        prop = ref[i];
        this.saves[prop] = console[prop];
      }
    }

    Debugger.prototype.enable = function(prop) {
      var results;
      if (prop && this.saves[prop]) {
        return console[prop] = this.saves[prop];
      } else {
        results = [];
        for (prop in this.saves) {
          results.push(console[prop] = this.saves[prop]);
        }
        return results;
      }
    };

    Debugger.prototype.disable = function(prop) {
      var results;
      if (prop && this.saves[prop]) {
        return console[prop] = function() {};
      } else {
        results = [];
        for (prop in this.debugFunctions) {
          results.push(console[prop] = function() {});
        }
        return results;
      }
    };

    return Debugger;

  })();

  module.exports = Debugger;

}).call(this);
