// Generated by CoffeeScript 1.10.0
(function() {
  var DNDProtocol;

  DNDProtocol = (function() {
    DNDProtocol.prototype.type = "Void";

    DNDProtocol.prototype.data = null;

    function DNDProtocol(type, data, event) {
      this.type = type;
      this.data = data;
      this.event = event;
    }

    return DNDProtocol;

  })();

  module.exports = DNDProtocol;

}).call(this);
