// Generated by CoffeeScript 1.10.0
(function() {
  window.onload = function() {
    var Buffer, Editor, VC, buffer, context, i, len, pack, packages;
    VC = VincentContext;
    Buffer = VC.require("/vincent/facility/buffer");
    Editor = VC.require("/vincent/editor");
    packages = [VC.require("/standard/editor.package/index")];
    window.editor = new Editor(document.body);
    for (i = 0, len = packages.length; i < len; i++) {
      pack = packages[i];
      editor.plugins.register(pack);
    }
    editor.init();
    context = editor.contextManager.create();
    buffer = editor.bufferManager.allocate(context);
    document.body.appendChild(buffer.node);
    buffer.activate();
    buffer.setContentString("");
    return editor.nextRender((function(_this) {
      return function() {
        return editor.bufferManager.focusAt(buffer);
      };
    })(this));
  };

}).call(this);
